name: Update flake inputs

on:
  workflow_dispatch:
  push:
    branches:
      - action-test

jobs:
  update-flake:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update flake inputs
        run: nix flake update

      - name: Attempt to build flake
        run: nix build

      - name: Test on Hyprland
        env:
          XDG_RUNTIME_DIR: /home/runner/runtime
          WLR_BACKENDS: headless
          WLR_LIBINPUT_NO_DEVICES: 1
          WAYLAND_DISPLAY: wayland-1
          GTK_USE_PORTAL: 0
        run: |
          mkdir $XDG_RUNTIME_DIR
          chown $USER $XDG_RUNTIME_DIR
          chmod 0700 $XDG_RUNTIME_DIR

          nix profile install 'nixpkgs#hyprland'
          Hyprland &
          sleep 5  # Give Hyprland some time to start
          hyprctl -i 0 dispatch exec "$(pwd)/result/bin/caelestia-shell"
          sleep 5  # Give the shell some time to start
          pgrep .caelestia-shell || exit 1  # Fail job if shell died

          hyprctl -i 0 dispatch exec "$(pwd)/result/bin/caelestia-shell kill"
          hyprctl -i 0 dispatch exit
          true  # Clean exit

      - name: Check for changes
        id: check
        run: echo modified=$(test -n "$(git status --porcelain)" && echo 'true' || echo 'false') >> $GITHUB_OUTPUT

      # - name: Commit and push changes
      #   if: steps.check.outputs.modified == 'true'
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: flake.lock
      #     default_author: github_actions
      #     message: "[CI] chore: update flake"
